SELECT * FROM movies WHERE Id = 6;
SELECT * FROM movies WHERE Year BETWEEN 2000 AND 2010;
SELECT * FROM movies WHERE Year NOT BETWEEN 2000 AND 2010;
SELECT Title, Year FROM movies WHERE Id BETWEEN 1 AND 5;