SELECT DISTINCT Director FROM Movies ORDER BY Director ASC;
SELECT * FROM Movies ORDER BY Year DESC LIMIT 4;
SELECT * FROM Movies ORDER BY Title ASC LIMIT 5;
SELECT * FROM Movies ORDER BY Title ASC LIMIT 5 OFFSET 5;